# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y4vO1zvlMOPk9qwXS6a1u5wR9xeMpBAu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error ,mean_squared_error,r2_score

df=pd.read_csv("/content/ev_car_India_dataset.csv")

print(df.head())

print(df.shape)

df.isnull().sum()

df["Model"].unique()

x=df.drop("Price",axis=1)
y=df["Price"]

categorical=["Brand","Model"]
numericcal=["Range","Power","Battery"]

preprocessor=ColumnTransformer([
    ("numericcal",StandardScaler(),numericcal),
    ("categorical",OneHotEncoder(handle_unknown="ignore"),categorical)])

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

alphas=[0.01,0.1,10,100]
result=[]
for alpha in alphas:
  model=Pipeline([
      ("preprocessor",preprocessor),
      ("ridge",Ridge(alpha=alpha))
  ])

model.fit(x_train,y_train)

train_pred=model.predict(x_train)
test_pred=model.predict(x_test)

train_mae=mean_absolute_error(y_train,train_pred)
train_rmse=np.sqrt(mean_squared_error(y_train,train_pred))
train_r2=r2_score(y_train,train_pred)

test_mae=mean_absolute_error(y_test,test_pred)
test_rmse=np.sqrt(mean_squared_error(y_test,test_pred))
test_r2=r2_score(y_test,test_pred)

result.append({alpha,train_mae,train_rmse,train_r2,test_mae,test_rmse,test_r2})

print (result)

result=pd.DataFrame(result,columns=["alpha","train_mae","train_rmse","train_r2","test_mae","test_rmse","test_r2"])

print("/nRidge Regression Result:")
print(result)

